---
title: "Exploratory Analysis on cases adjusted by PCR tests"
output: html_notebook
---

```{r setup}
library(tidyverse)
library(here)
library(modelr)

source(here("functions", "retrieve_tests_cases_region.R"))
```

Retrieve data
```{r}
examenes_casos_rm <- 
  retrieve_tests_cases_region() %>% 
  filter(Region == "Metropolitana")

max_fecha <- 
  examenes_casos_rm %>% 
  pull(Fecha) %>% max()
```

Exploratory plot: Cases vs Tests
```{r}
examenes_casos_rm %>% 
  mutate(Mes = lubridate::month(Fecha, label = TRUE)) %>% 
  ggplot(aes(N_Tests, N_Casos, color = Mes)) +
  geom_point() +
  geom_smooth(method = "lm")
```

## Regressions by week
```{r}
# Get median of daily tests
median_tests <- 
  examenes_casos_rm %>% 
  pull(N_Tests) %>% 
  median()

# Nest by week and run regressions
casos_pred_model1 <- 
  examenes_casos_rm %>% 
  nest(data = c(-semana)) %>% 
  mutate(reg_casos = map(data, ~lm(N_Casos ~ N_Tests, data = .)),
         pred_with_median_tests = map_dbl(reg_casos, ~predict(., newdata = tibble(N_Tests = 10000))))
```

First plot:
```{r}
examenes_casos_rm_filt <- 
  examenes_casos_rm %>% 
  filter(lubridate::isoweek(semana) %in% c(31, 35, 40, 49, 51, 53)) %>% 
  left_join(casos_pred_model1,
            by = "semana")

examenes_casos_rm_last2days <- 
  examenes_casos_rm_filt %>% 
  filter(Fecha %in% c(lubridate::ymd(20201217, 20201219, 20201218, 20201220)))

examenes_casos_rm_filt %>% 
  ggplot(aes(N_Tests, N_Casos, color = factor(semana))) +
  geom_point() +
  geom_smooth(method = "lm", fullrange = TRUE, se = FALSE) +
  ggrepel::geom_label_repel(data = examenes_casos_rm_last2days,
                            aes(label = as.character(Fecha))) +
  labs(
    subtitle = "Data for Metropolitan Region, Chile",
    x = "Number of Tests",
    y = "Number of Cases",
    color = "Week")
```

Second plot:
```{r}
ggplot(examenes_casos_rm_filt,
       aes(N_Tests, N_Casos, color = factor(semana))) +
  geom_point() +
  geom_vline(xintercept = 10000, color = "blue4") +
  geom_point(aes(x = 10000, y = pred_with_median_tests), size = 5,
             show.legend = FALSE) +
  geom_smooth(method = "lm",
              fullrange = TRUE,
              se = FALSE) +
  labs(
    subtitle = "Data for Metropolitan Region, Chile",
    x = "Number of Tests",
    y = "Number of Cases",
    color = "Week") +
  annotate("label",
           x = 10000*0.95,
           y = 1000,
           label = "10.000 daily tests",
           color = "blue4")
```

